src/networkIdleObservable.ts
test/e2e/images6/index.html
test/e2e/images6/index.spec.ts

It seems like `img.complete` isn't exactly what you might expect in this edge case, in Chromium.

PERF-784 img.complete not detected correctly in Chromium

---

playwright.config.ts
test/e2e/interaction3/index.spec.ts

Run our end-to-end test suite against mobile browsers.  We only run this on CI so that local testing doesn't get too bogged down.

Test against mobile browsers (only on CI)

---

AUTHORS

We especially want to be able to highlight some contributions that occurred prior to extracting this library  as an open source project.
The AUTHORS file appears to be a fairly standardized means of doing so.
https://opensource.google/documentation/reference/releasing/authors
https://github.com/facebook/react/blob/main/AUTHORS
I am adding myself for now, and will invite others to include themselves in this list!

PERF-795 recognize contributors via AUTHORS file

---

src/visuallyCompleteCalculator.ts

Some browsers (esp. Firefox) appear to report unreasonable timestamps for unknown reasons.  This doesn't seem like it can be valid data, so maybe we should help normalize the data by omitting those measurements?

Omit measurements larger than MAX_SAFE_INTEGER

---

.npmrc
package.json
scripts/ensure-yarn.js

This change is optional!
The idea is just to stop myself from accidentally forgetting which package manager the project uses and avoid committing _both_ `package-lock.json` and `yarn.lock` files.

Disallow `npm install`

---

test/e2e/interaction1/index.spec.ts

It seems like this click event can run before the event handler is attached in the latest firefox binary (99.0.1).

Fix a test assertion in latest firefox release

---

.npmrc
package.json
scripts/ensure-yarn.js

It seems that our pre-install hook isn't safe.  This runs when a package is installed in production, preventing use by some consumers.
I think the project I took this idea from was using workspaces.  This means they could specify this hook in the repo root package without impacting the published npm packages.  We can't get away with the same here.
Fixes #60

Revert "Disallow npm usage"

---

README.md
src/inViewportImageObserver.ts
src/visuallyCompleteCalculator.ts
test/e2e/output1/index.html
test/e2e/output1/index.spec.ts
test/e2e/output2/index.html
test/e2e/output2/index.spec.ts

Capture the last mutation and last image load data in the `detail` object reported by TTVC.  These can be useful to report to assist diagnosing regressions in the field.

PERF-813 Capture diagnostic details

---

package.json

This should be an http link, so that it can be displayed in npmjs.com.

Update repository link

---

README.md
src/index.ts
src/visuallyCompleteCalculator.ts

This is the simplest version of this feature.  I'm open to adding some cancellation reasons & logging, but I couldn't come up with an obvious solution for how to report those results back.
The [web-vitals](https://github.com/GoogleChrome/web-vitals) project doesn't appear to have any patterns we can lean on for that capability either.

Add cancel() function to public API

---

README.md
src/index.ts
src/visuallyCompleteCalculator.ts
test/e2e/bfcache/about.html
test/e2e/bfcache/index.html
test/e2e/bfcache/index.spec.ts
test/server/server.mjs

This change builds instrumentation for navigations enhanced by browser back/forward caches into the library.
This uses the `pageshow` event and it's `.persisted` property to identify a navigation and trigger a new measurement.
NOTE: This change bakes into the library that we should start a new measurement for TTVC whenever a page is restored from the back/forward cache.  I _think_ this is almost always desirable, and therefore a good default, but I am not certain.
It's possible for a user to accomplish this today in user space, by importing the `start()` method and calling it manually.  It would also be possible to make this an opt-out configuration property.
~~I think a related question is how or whether we should let the user know that the measurement was started via back/forward cache …

Instrument back/forward cache navigations

---

README.md

It seems like GitHub changed the URL format expected for these badges.
https://github.com/badges/shields/issues/8671
Before: https://github.com/dropbox/ttvc/blob/97b5942336f4a69fd8b5f14652efd3177cce03da/README.md
After: https://github.com/dropbox/ttvc/blob/6f11af9cd7bfd41d2c7b3403e3119de396c884e3/README.md

Fix broken github badges

---

src/.eslintrc.yaml
src/index.ts
src/navigationEntry.ts
src/util/types.ts
src/visuallyCompleteCalculator.ts
test/e2e/spa1/index.spec.ts
test/e2e/spa2/index.spec.ts
test/e2e/spa3/index.spec.ts
test/e2e/spa4/index.spec.ts
test/e2e/spa5/index.spec.ts

Older browsers do not have support for PerformanceNavigationTiming. This changes adds fallback for getting navigation type from the deprecated `window.performance.navigation.type` when PerformanceNavigationTiming is not available.
Since `activationStart` is also on PerformanceNavigationTiming, we move this into a helper in the same file as well.
Finally, we can override the built-in browser declarations to get better typing for `getEntriesByType`, `activationStart`, and `document.prerendering`. This allows us to remove the override for `@typescript-eslint/ban-ts-comment` eslint rule since the default is pretty reasonable (`ts-expect-error` is allowed with description) https://typescript-eslint.io/rules/ban-ts-comment/

Improve handling around performance navigation entry

---

src/index.ts
src/visuallyCompleteCalculator.ts
test/e2e/prerender1/index.spec.ts
test/e2e/prerender1/index2.html

This change fixes two issues with the prerender support:
* Soft navigation on a prerendered page should still have `script` navigation type
* Instead of restarting measuring on `prerenderingchange`, we wait for it to init if the document is currently prerendering. This method is described in https://developer.chrome.com/blog/prerender-pages/#impact-on-analytics
Since we are comparing `start` with `activationStart`, restarting measurement doesn't make sense since that would cause `start` to always be slightly after `activationStart` and therefore cause the initial navigation to a prerendered page to be classified as a soft navigation. Waiting for activation and not restarting measurement works better.
This also adds a new test case to the existing prerender tests to perform a soft …

Soft navigation on a prerendered page should still have `script` navigation type

---

src/networkIdleObservable.ts

`window?.MutationObserver` raises a `ReferenceError` when `window` is not defined (e.g. in Node.js). This code path gets hit just on import. This can be problematic particularly in unit tests and SSR.
Added a `typeof` guard which should make it not raise error on import.

Make library import safe in non-browser environments

---

.gitignore
README.md
src/index.ts
src/visuallyCompleteCalculator.ts
test/e2e/interaction1/index.spec.ts
test/e2e/interaction2/index.spec.ts
test/e2e/interaction3/index.spec.ts
test/e2e/interaction4/index.html
test/e2e/interaction4/index.spec.ts
test/server/public/analytics.js
test/util/entries.ts

We want to log the reason why TTVC measurement was cancelled. The most accurate way would be to implement that functionality in the library itself, especially considering that we will add more diagnostic information down the line.
This implements a simple interface to add listeners to diagnostic events.
1. Good way to test this would be to build the package, launch the express server and run `interaction1` e2e test case, performing a click/keydown/tab switch while the page is still loading. Diagnostic with the reason for measurement cancellation will be logged as a warning to the console.

Adding cancellation reason diagnostics

---

README.md

This documents my workflow for publishing new versions of `@dropbox/ttvc` to npm!
View repo files for this branch: https://github.com/dropbox/ttvc/tree/add-release-documentation

Add "Releasing" documentation to project README

---

README.md
src/index.ts
src/visuallyCompleteCalculator.ts
test/e2e/cancellation1/index.html
test/e2e/cancellation1/index.spec.ts
test/e2e/cancellation2/index.html
test/e2e/cancellation2/index.spec.ts

Currently, TTVC will invoke error callback for every call of `cancel` (manual measurement cancellation). Meaning that if the measurement was manually cancelled from two different places, two errors will be reported.
This refactors the code to only invoke error callback once per manual cancellation.
Additionally, this fixes a bug where `eventType` passed to manual `cancel` method was not getting all the way through to the error callback.
- Added two additional playwright scripts to catch regressions specifically with manual cancellations.

Logging only the first manual cancellation of the measurement

---

src/index.ts
src/visuallyCompleteCalculator.ts
test/e2e/cancellation1/index.html
test/e2e/cancellation2/index.html
test/e2e/spa6/index.html
test/e2e/spa6/index.spec.ts

While working on tighter integration of TTVC measurements of "soft" navigations, I have ran into an issue. While it is admittedly an edge case it still warrants a fix: **when a soft navigation occurs before the measurement has had a chance to complete, the interrupted navigation will not be reported entirely correctly.**
The diagram below might help understand the issue:
1. Measurement cancellation will be reported much later compared to when it actually occurred, making integration of TTVC into a host application more confusing
2. Duration of the measurement cancellation will also be incorrect
Along the way, I have also addressed a few edge case scenarios:
1. I have introduced a `NEW_MEASUREMENT` cancellation reason, which is slightly distinct from `NEW_NAVIGATION`. `NEW_NAVIGATION` …

Starting a new TTVC measurement will now cancel out the previous measurement, if it is still active

---

README.md

I realised that I should have updated the docs with the most recent changes from #85

Updating the docs

---

test/e2e/animation1/index.html
test/e2e/animation1/index.spec.ts

I want to ensure that css animations don't affect TTVC in its current implementation, so I've added a small test to verify this
can be run with `npx playwright test test/e2e/animation1/index.spec.ts --ui`

confirm ttvc is not affected by animation delay

---

src/index.ts

This is a follow up to #78.  This further improves the behaviour of the library by ensuring that simply importing the library will not attempt to trigger any side effects.

getNetworkIdleObservable should not be called on import
